id = "elsa"
name = "Elsa"
version = "0.1.0"
schema_version = 1
authors = [
    "MrPoloGit",
]
description = "Syntax highlighting for the Elsa lambda calculus teaching language (.lc files)"
repository = "https://github.com/MrPoloGit/zed-elsa"

[grammars.elsa]
repository = "https://github.com/MrPoloGit/tree-sitter-elsa"
rev = "ea156226ffcc0659b7e1a7d1f94fcf204df73d2c"
